CREATE DATABASE IF NOT EXISTS auth_db;
CREATE DATABASE IF NOT EXISTS account_db;
CREATE DATABASE IF NOT EXISTS order_db;
CREATE DATABASE IF NOT EXISTS payment_db;


CREATE USER IF NOT EXISTS 'shop'@'%' IDENTIFIED BY 'shop';
GRANT ALL PRIVILEGES ON auth_db.*    TO 'shop'@'%';
GRANT ALL PRIVILEGES ON account_db.* TO 'shop'@'%';
GRANT ALL PRIVILEGES ON order_db.*   TO 'shop'@'%';
GRANT ALL PRIVILEGES ON payment_db.* TO 'shop'@'%';
FLUSH PRIVILEGES;